config/routes.rb
Rails.application.routes.draw do
  resources :offers, only: %i(index create update edit)
  root 'offers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates_presence_of :name, :advertiser
  validates_numericality_of :payout
  validate :validate_currency

  private

  def validate_currency
    errors.add(:payout, 'should be at least 0.01') if payout.nil? || payout < 0.01
  end
end

app/controllers/application_controller.rb
require 'application_responder'
class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  # protect_from_forgery with: :exception
end

app/controllers/concerns/serialized.rb
module Serialized
  extend ActiveSupport::Concern

  def render_errors(object)
    render plain: object.errors.full_messages.join(', '), status: :forbidden
  end

  def render_json_message(message)
    render json: { message: message }, status: :ok
  end

  def publish_broadcast(item, target = controller_name.singularize)
    if item.errors.any?
      render_errors(item)
    else
      file = helpers.c("#{controller_name}_#{target}", target.to_sym => item)

      ActionCable.server.broadcast target, message: file, id: item.id
      render_json_message('')
    end
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  include Serialized

  before_action :load_offer, only: %i(edit update)

  respond_to :json, only: %i(create update edit)

  def index
    @offers = Offer.order(created_at: :desc)
  end

  def create
    @offer = Offer.create(strong_params)
    publish_broadcast @offer
  end

  def edit
    @offer = Offer.find(params[:id])
    render json: helpers
      .c("#{controller_name}_offer-form",
         offer: @offer, id: "edit_offer#{@offer.id}", m: 'PATCH', tclass: 'js-form-edit')
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(strong_params)
    publish_broadcast @offer
  end

  private

  def load_offer
    @offer = Offer.find(params[:id])
  end

  def strong_params
    params.require(:offer).permit(:name, :advertiser, :payout)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_flash
    javascript_tag('App.flash = JSON.parse(' "'#{j({ success: flash.notice, error: flash.alert }.to_json)}'" ');')
  end

  def v_component(component_name, locals = {}, &block)
    path = component_name.split('_').first
    name = component_name.split('_').last
    render("#{path}/#{name}", locals, &block)
  end

  def component(component_name, locals)
    path = component_name.split('_').first
    name = component_name.split('_').last
    ApplicationController.render file: "/#{path}/_#{name}", locals: locals, layout: false
  end

  alias c component
  alias v v_component
end

app/views/application/_offer.html.slim
.list-group-item.js-offers--content id="offerId#{offer.id}"
  .row
    .col-3
      = offer.name
    .col-3
      = offer.advertiser
    .col-2
      = offer.payout
    .col-1
      = link_to 'edit', edit_offer_path(offer), method: 'get',
        data: {remote: true, type: :json, target: "#offerId#{offer.id}"},
        class: 'btn btn-warning js-offer-common-edit'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag  'application', media: 'all' %>
  </head>

  <body class="body js-disable-events">
    <div class="container main">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/shared/_footer.html.slim
footer.footer.pb-2.text-lighten
  .container-fluid
    .row
      hr.mb-3
      .col-sm-6
        p.text-center-xs &copy 2017 (c)
      .col-sm-6.hidden-xs

app/views/layouts/shared/_js_locales_info.html.slim
= javascript_tag do
  |  I18n.defaultLocale = "
  = I18n.default_locale
  | "; I18n.locale = "
  = I18n.locale
  | "; I18n.fallbacks = true; 

app/views/offers/_offer-form.html.slim
= form_for offer, method: m, html: { role: 'form', class: "#{tclass}", id: id},
  data: { remote: true, type: :json } do |f|
  .form-row
    .col-3
      = f.text_field :name, class: 'form-control', required: true, placeholder: 'Name'
    .col-3
      = f.text_field :advertiser, class: 'form-control', required: true, placeholder: 'Advertiser'
    .col-2
      = f.text_field :payout, class: 'form-control', required: true, placeholder: 'Payout'
    .col-1
      = f.button 'submit', class: 'btn btn-primary js-message-create-submit'

app/views/offers/_offer.html.slim
.list-group-item.js-offers--content id="offerId#{offer.id}"
  .row
    .col-3
      = offer.name
    .col-3
      = offer.advertiser
    .col-2
      = offer.payout
    .col-1
      = link_to 'edit', edit_offer_path(offer), method: 'get',
        data: {remote: true, type: :json, target: "#offerId#{offer.id}"},
        class: 'btn btn-warning js-offer-common-edit'

app/views/offers/index.html.slim
h1.text-center Manage offers
h3 Add offer:
.list-group-item
  = c("#{controller_name}_offer-form", { offer: Offer.new, id: 'new_offer', m: 'POST', tclass: 'js-form-new'} )
#offers
  = render @offers